apiVersion: apps/v1
kind: Deployment
metadata:
        name: deploymentapp
        labels:
             app: deploymentapp
spec: 
    replicas: 1
    strategy: 
        type: RollingUpdate
    template:
          metadata: 
                name: deploymentapp 
                labels:
                    app: deploymentapp
          spec:
              containers:
                  - name: deploymentapp
                    image: ubuntu:latest
                    resources:
                        requests:
                            cpu: "25m"
                            memory: "50Mi"
                        limits:
                           cpu: "50m"
                           memory: "100Mi"    
                    ports:
                        - name: http
                          containerPort: 80
                          protocol: TCP     
    selector:
      matchLabels:
              app: deploymentapp
---
apiVersion: autoscaling/v2
kind:  HorizontalPodAutoscaler
metadata:
       name: hpa1
       labels: 
           app: hpa1
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: deploymentapp
    minReplicas: 1
    maxReplicas: 2
    metrics:
     - type: Resource
        resource:
         name: cpu
         target:
           type: Utilization
           averageUtilization: 50



            
             
