apiVersion: apps/v1
kind: Deployment
metadata:
        name: deploymenthpa
        labels:
             app: deploymenthpa
spec: 
    replicas: 1
    strategy: 
        type: RollingUpdate
    template:
          metadata: 
                name: deploymenthpa 
                labels:
                    app: deploymenthpa
          spec:
              containers:
                  - name: http
                    image: nginx:latest
                    resources:
                        requests:
                            cpu: "25m"
                            memory: "50Mi"
                        limits:
                           cpu: "50m"
                           memory: "100Mi"    
                    ports:
                        - name: http
                          containerPort: 80
                          protocol: TCP     
    selector:
      matchLabels:
              app: deploymenthpa
---
apiVersion: autoscaling/v2
kind:  HorizontalPodAutoscaler
metadata:
       name: deploymenthpa
       labels: 
           app: deploymenthpa
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: deploymenthpa
    minReplicas: 1
    maxReplicas: 2
    metrics:
     - type: Resource
       resource:
           name: cpu
           target:
             type: Utilization
             averageUtilization: 50



            
             
